resolver: lts-24.45

packages:
  - apecs
  - apecs-physics
  - apecs-gloss
  - apecs-gloss-3d
  - apecs-box2d
  - apecs-box3d
  - apecs-stm
  - examples

allow-newer: true

extra-deps:
  - git: https://gitlab.com/dpwiz/box-nd
    commit: d962162c67fa33d53b943d2446a30b4f3742e343
    subdirs:
      - Box2D
      - Box3D
  - gloss-export-0.1.0.4

nix:
  pure: false
  packages:
    - libGL
    - freeglut
    - mesa_glu
    - zlib

system-ghc: true
install-ghc: false
